[package]
org = "ballerinax"
name = "slack"
version = "0.9.7"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["slack"]
repository = "https://github.com/ballerina-platform/module-ballerinax-slack"

[build-options]
observabilityIncluded = true
